#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 Northeastern University
# SPDX-License-Identifier: Apache-2.0
"""Turn the output of gen_golden (one GOLDEN / GOLDEN_HASH line per case) into the
C++ header of golden vectors shared by libe3's and OCUDU's tests.

usage: gen_header.py <golden.txt> <flexric-commit> <namespace> [spdx-years-holder-license] > e2sm_dapp_golden.hpp

The optional fourth argument is "ocudu" to emit the SPDX header OCUDU's REUSE check expects.
"""
import sys

src, commit, ns = sys.argv[1], sys.argv[2], sys.argv[3]
ocudu = len(sys.argv) > 4 and sys.argv[4] == "ocudu"
vectors, hashes = [], []
for line in open(src):
    parts = line.split()
    if not parts:
        continue
    if parts[0] == "GOLDEN":
        vectors.append((parts[1], parts[2]))
    elif parts[0] == "GOLDEN_HASH":
        hashes.append((parts[1], int(parts[2]), parts[3]))

# REUSE-IgnoreStart
if ocudu:
    print("// SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited")
    print("// SPDX-License-Identifier: BSD-3-Clause-Open-MPI")
else:
    print("// SPDX-FileCopyrightText: Copyright (c) 2026 Northeastern University")
    print("// SPDX-License-Identifier: Apache-2.0")
# REUSE-IgnoreEnd
print("//")
print("// GENERATED by tools/e2sm_dapp_golden (libe3), do not edit by hand.")
print("// APER encodings of every E2SM-DAPP message, produced by flexric's own")
print(f"// dapp_enc_*_asn() at commit {commit}. They are the byte-compatibility")
print("// contract between flexric, libe3 and OCUDU. The inputs are listed in")
print("// tools/e2sm_dapp_golden/gen_golden.c.")
print()
print("#pragma once")
print()
print("#include <cstddef>")
print("#include <cstdint>")
print()
print(f"namespace {ns} {{")
print()
print("struct golden_vector {")
print("  const char* name;")
print("  const char* hex;")
print("};")
print()
print("// Inlined: the encoding is small enough to read.")
print("inline constexpr golden_vector golden_vectors[] = {")
for n, h in vectors:
    print(f'    {{"{n}", "{h}"}},')
print("};")
print()
print("struct golden_hash {")
print("  const char*    name;")
print("  std::size_t    length;")
print("  std::uint64_t  fnv1a64;")
print("};")
print()
print("// Too large to inline: the encoded length and its FNV-1a 64-bit hash.")
print("inline constexpr golden_hash golden_hashes[] = {")
for n, l, h in hashes:
    print(f'    {{"{n}", {l}, 0x{h}ULL}},')
print("};")
print()
print(f"}} // namespace {ns}")
