// SPDX-FileCopyrightText: Copyright (c) 2026 Northeastern University
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/e2sm_dapp_golden (libe3), do not edit by hand.
// APER encodings of every E2SM-DAPP message, produced by flexric's own
// dapp_enc_*_asn() at commit 71631466bb32d8f1172f6b932ec79d8ae25034eb. They are the byte-compatibility
// contract between flexric, libe3 and OCUDU. The inputs are listed in
// tools/e2sm_dapp_golden/gen_golden.c.

#pragma once

#include <cstddef>
#include <cstdint>

namespace libe3_e2sm_dapp_test {

struct golden_vector {
  const char* name;
  const char* hex;
};

// Inlined: the encoding is small enough to read.
inline constexpr golden_vector golden_vectors[] = {
    {"et_f1", "00"},
    {"ad_style1", "00010100"},
    {"ad_style2", "00010200"},
    {"ad_style_max", "000500ffffffff00"},
    {"ih1_full", "0e00ff0007000200f1102004d200050817979cfe3d85cd15012a"},
    {"ih1_min", "0000ff000100001300140000"},
    {"ih1_bounds", "0e000060ffffffff00ffffffff60ffffffff60ffffffff087fffffffffffffff087fffffffffffffff"},
    {"ih2_full", "2e0200f1102004d200050817979cfe3d85cd15012a"},
    {"ih2_min", "20011300140063"},
    {"im1_small", "0000040003deadbeef"},
    {"im1_one", "000001000000"},
    {"im2_empty", "200000"},
    {"im2_one", "2000010001000001"},
    {"im2_multi", "20000200070800010002000330ffffffff04000060ffffffff"},
    {"ch1_full", "18ff00070817979cfe3d85cd15012a"},
    {"ch1_min", "00010002"},
    {"ch1_bounds", "1bffffffff0000087fffffffffffffff087fffffffffffffff"},
    {"cm1_small", "0000030002010203"},
    {"cm1_one", "0000010000ff"},
    {"co1_full", "1c0817979cfe3d85cd15012a0a102030405060708090a0"},
    {"co1_min", "00"},
    {"co1_tsseq", "180817979cfe3d85cd15012a"},
    {"co1_payload", "040a102030405060708090a0"},
    {"fd_min", "00104532534d2d4441505000001a312e332e362e312e342e312e35333134382e312e312e3235352e331100444150502053657276696365204d6f64656c20666f722045322f453320627269646765"},
    {"fd_report", "20104532534d2d4441505000001a312e332e362e312e342e312e35333134382e312e312e3235352e331100444150502053657276696365204d6f64656c20666f722045322f453320627269646765400101068045332044617461205265706f7274010101014001020900453320537562736372697074696f6e204d6170010201020002000704000100020009000003"},
    {"fd_full", "70104532534d2d4441505000001a312e332e362e312e342e312e35333134382e312e312e3235352e331100444150502053657276696365204d6f64656c20666f722045322f453320627269646765200101068045332044617461205265706f7274010101014001020900453320537562736372697074696f6e204d617001020102000200070400010002000900000320010105806441707020436f6e74726f6c010101010101000100070400010002"},
    {"fd_ctrl", "50104532534d2d4441505000001a312e332e362e312e342e312e35333134382e312e312e3235352e331100444150502053657276696365204d6f64656c20666f722045322f45332062726964676500010105806441707020436f6e74726f6c010101010101"},
};

struct golden_hash {
  const char*    name;
  std::size_t    length;
  std::uint64_t  fnv1a64;
};

// Too large to inline: the encoded length and its FNV-1a 64-bit hash.
inline constexpr golden_hash golden_hashes[] = {
    {"im1_max", 32773, 0xf1a4af710fb93cc5ULL},
    {"im2_255", 1464, 0x19011514fbcfc2deULL},
    {"im2_256", 1473, 0x74d95212a317dbb8ULL},
    {"cm1_large", 16005, 0x5250310ee619ccfeULL},
};

} // namespace libe3_e2sm_dapp_test
